# Generated by Django 5.1.5 on 2025-01-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiapp',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academiapp',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academiapp',
            name='number',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academiapp',
            name='pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academiapp',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
