# Generated by Django 5.1.5 on 2025-01-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0003_academiapp_course_academiapp_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiapp',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='number',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='pin',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
