# Generated by Django 5.1.5 on 2025-01-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0004_alter_academiapp_course_alter_academiapp_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiapp',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='number',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
