# Generated by Django 5.1.5 on 2025-01-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0005_alter_academiapp_course_alter_academiapp_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiapp',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
