# Generated by Django 5.1.5 on 2025-01-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0008_alter_portfolio_user_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
