# Generated by Django 5.1.5 on 2025-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0012_studentmarks_delete_academicperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiapp',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
