# Generated by Django 5.1.5 on 2025-02-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0013_academiapp_is_approved_alter_academiapp_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiapp',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academiapp',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
