# Generated by Django 5.1.5 on 2025-02-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0014_alter_academiapp_number_alter_academiapp_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiapp',
            name='is_approved',
        ),
    ]
