# Generated by Django 5.1.5 on 2025-02-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0017_academicrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicRecord',
        ),
    ]
