# Generated by Django 5.1.5 on 2025-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiApp', '0018_delete_academicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('facility_type', models.CharField(choices=[('library', 'Library'), ('lab', 'Laboratory'), ('sports', 'Sports Complex'), ('canteen', 'Canteen'), ('auditorium', 'Auditorium')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
